### ISSUE TITLE
Combining data CSVs

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/cloud9#4]

**Comment by ChadNeald** [comment]
Done most of this as a group. @rtaph and @elina-linglin go back and attempt with Dask.

**Comment by ChadNeald** [comment]
Everyone report time and memory usage here as well!

**Comment by ChadNeald** [comment]
Commands for R and Python

R -> pryr::mem_used() 
R -> system.time()
R -> library(tictoc)
R -> tic()
R -> toc()

Python -> %%time
Python -> %memit

**Comment by rtaph** [comment]
Mine took 1 min 17 s to load, using 10.4 GB of memory (code [here](https://github.com/rtaph/cloud9/blob/0010edaea325293d6da0d6fd0675093f382f267c/notebook/notebook.ipynb)). Not super efficient with `pd.concat`, but it works. I tried some other approaches to reduce the memory footprint, but didn't get very far. Got a bunch of memory leaks (or key errors) when trying to delete intermediary results in a while loop.

**Comment by ChadNeald** [comment]
Mine crashed. I waited 20+ minutes with no end in sight. I'll try again later and wait longer but had to restart so I could go to lecture.

**Comment by ChadNeald** [comment]
Update: I realized Gittu had a cell in his notebook for combining the data so I used a similar structure and got it to run. It took 15 minutes and had a peak memory of about 2.7 GB. From the small tests I did I think the method in the notebook we have is faster but uses up more memory compared to what Gittu used. We can chat about it in today's meeting.
